spring:
#  datasource:
#    driver-class-name: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://47.115.201.125:5236?schema=PRODUCTION
#    username: SYSDBA
#    password: SYSDBA001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/template
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 1689411538@qq.com
    password: lxvtoyflfydrcehi
    properties:
      from: 1689411538@qq.com
  # 移除Redis配置
  # data:
  #   redis:
  #     database: 0
  #     host: #
  #     port: 6379
  #     password: