#application.yaml
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/template
    username: root
    # password 在 application-local.yaml 中配置
  mail:
    host: smtp.qq.com
    port: 587
    # username, password, from 在 application-local.yaml 中配置
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.qq.com
